# Generated by Django 5.2.7 on 2025-10-23 15:32

import core.models.auth
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, max_length=128, null=True)),
                ('img', models.ImageField(upload_to='ctg/')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('hex', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('fio', models.CharField(max_length=56)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', core.models.auth.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Mebel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.PositiveIntegerField(default=0)),
                ('price_type', models.CharField(choices=[('usd', 'USD'), ('uzs', 'UZS'), ('rub', 'RUB')], max_length=3)),
                ('discount', models.SmallIntegerField(default=0)),
                ('material', models.CharField(max_length=256, null=True)),
                ('filled', models.CharField(max_length=128, null=True)),
                ('g_length', models.PositiveIntegerField(default=233)),
                ('g_width', models.PositiveIntegerField(default=107)),
                ('g_height', models.PositiveIntegerField(default=90)),
                ('is_spalniy', models.BooleanField(default=False)),
                ('s_length', models.PositiveIntegerField(blank=True, default=233, null=True)),
                ('s_width', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('s_height', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('extra', models.JSONField(default=dict)),
                ('color', models.ManyToManyField(related_name='colors', to='core.color')),
                ('ctg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('total_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
                ('mebel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcart', to='core.mebel')),
            ],
        ),
        migrations.CreateModel(
            name='MebelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='2025/10/23/mebel/')),
                ('mebel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.mebel')),
            ],
        ),
    ]
